Repository killkelleyr/stock_sim, pull requests merged in 2020-06, with the labels that each got.

#8 issue-2-creation_module: added the user table with all information
  stock_sim/databaseTables/userName.sql
  stock_sim/modules/.keep
Labels: backend, database

#9 Branch: Issue-2-user-creation-module
  setup.py
  stock_sim/__init__.py
  stock_sim/cli/__init__.py
  stock_sim/cli/stockSim.py
  stock_sim/databaseTables/__init__.py
  stock_sim/modules/__init__.py
  stock_sim/modules/dbReader.py
  stock_sim/modules/dbWriter.py
  stock_sim/modules/userName.py
Labels: backend, database

#11 fixed bugs with setup.py file, package now installs correctly
  setup.py
Labels: bug

#17 wrong database name used
  stock_sim/databaseTables/userName.sql
Labels: bug

#19 Issue 4 logging utility
  .gitignore
  stock_sim/modules/.keep
  stock_sim/modules/logger.py
Labels: backend

#21 Issue 20 update existing modules to use new logger module
  stock_sim/modules/dbReader.py
  stock_sim/modules/dbWriter.py
  stock_sim/modules/stock.py
  stock_sim/modules/userName.py
Labels: backend

#25 Issue 22 create basic ui
  stock_sim/cli/stockSim.py
Labels: UI, backend

#24 added volumn to imput
  stock_sim/modules/dbWriter.py
Labels: bug

#27 added clear statement upon calling
  stock_sim/cli/stockSim.py
Labels: UI, bug

#28 modified text wrapping to use the displays width and height
  stock_sim/cli/stockSim.py
Labels: UI, bug

#35 updated modules to properly import the logger module
  stock_sim/modules/buy_sell.py
  stock_sim/modules/dbReader.py
  stock_sim/modules/dbWriter.py
  stock_sim/modules/stock.py
  stock_sim/modules/userName.py
Labels: bug

#36 Issue 32 user home screen
  stock_sim/cli/stockSim.py
Labels: UI, feature

#37 Issue 32 user home screen
  stock_sim/databaseTables/userName.sql
  stock_sim/modules/dbWriter.py
  stock_sim/modules/userName.py
Labels: bug

#38 added username screen, and added user to home_screen
  stock_sim/cli/stockSim.py
Labels: UI, feature

#40 changed header
  stock_sim/databaseTables/Transaction_history.sql
Labels: bug

#41 updated user variable
  stock_sim/cli/stockSim.py
Labels: feature

#42 Issue 31 stock lookup screen
  stock_sim/cli/stockSim.py
  stock_sim/modules/stock.py
Labels: UI, feature

#45 inital porfolio class
  stock_sim/modules/portfolio.py
Labels: backend
